language: rust
env: RUST_BACKTRACE=full
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - apt-get install tree
  - tree
  - cargo install -f rustfmt || cargo fmt -- --version || exit 0
  - cargo build --verbose --all
  - cargo test --verbose --all -- --nocapture
  - cargo build --release --verbose
  - cargo test --release --verbose